apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-store-service-account
  namespace: default
  annotations:
    iam.gke.io/gcp-service-account: "api-store@hazel-sky-254210.iam.gserviceaccount.com"